### ISSUE TITLE
app held up after "play" voice command

### ISSUE THREAD

**Issue by dominicafonso** [google/aiyprojects-raspbian#306] opened 2018-03-14 16:17 UTC
in normal use, the voice assistant (master branch) responds to hey google questions sequentially without any problems. I have implemented a youtube track player, saying hey google "play trackname" works but the voice recognizer app can't then receive further play commands. Here's the output from $ sudo journalctl -u voice-recognizer -n 30 -f

```
Mar 13 10:25:36 raspiaiy systemd[1]: Started voice recognizer.
Mar 13 10:25:39 raspiaiy python3[13780]: [2018-03-13 10:25:39,264] INFO:root:ON_MUTED_CHANGED:
Mar 13 10:25:39 raspiaiy python3[13780]: {'is_muted': False}
Mar 13 10:25:39 raspiaiy python3[13780]: [2018-03-13 10:25:39,267] INFO:root:ON_START_FINISHED
Mar 13 10:25:39 raspiaiy python3[13780]: [2018-03-13 10:25:39,268] INFO:main:ready...
Mar 13 10:25:44 raspiaiy python3[13780]: [2018-03-13 10:25:44,655] INFO:root:ON_CONVERSATION_TURN_STARTED
Mar 13 10:25:44 raspiaiy python3[13780]: [2018-03-13 10:25:44,656] INFO:main:listening...
Mar 13 10:25:52 raspiaiy python3[13780]: [2018-03-13 10:25:52,912] INFO:root:ON_END_OF_UTTERANCE
Mar 13 10:25:52 raspiaiy python3[13780]: [2018-03-13 10:25:52,913] INFO:main:thinking...
Mar 13 10:25:52 raspiaiy python3[13780]: [2018-03-13 10:25:52,927] INFO:root:ON_RECOGNIZING_SPEECH_FINISHED:
Mar 13 10:25:52 raspiaiy python3[13780]: {'text': ''}
Mar 13 10:25:53 raspiaiy python3[13780]: [2018-03-13 10:25:53,086] INFO:root:ON_CONVERSATION_TURN_TIMEOUT
Mar 13 10:25:53 raspiaiy python3[13780]: [2018-03-13 10:25:53,087] INFO:root:ON_CONVERSATION_TURN_FINISHED:
Mar 13 10:25:53 raspiaiy python3[13780]: {'with_follow_on_turn': False}
Mar 13 10:25:53 raspiaiy python3[13780]: [2018-03-13 10:25:53,089] INFO:main:ready...
Mar 13 10:25:56 raspiaiy python3[13780]: [2018-03-13 10:25:56,953] INFO:root:ON_CONVERSATION_TURN_STARTED
Mar 13 10:25:56 raspiaiy python3[13780]: [2018-03-13 10:25:56,954] INFO:main:listening...
Mar 13 10:25:59 raspiaiy python3[13780]: [2018-03-13 10:25:59,671] INFO:root:ON_END_OF_UTTERANCE
Mar 13 10:25:59 raspiaiy python3[13780]: [2018-03-13 10:25:59,673] INFO:main:thinking...
Mar 13 10:25:59 raspiaiy python3[13780]: [2018-03-13 10:25:59,685] INFO:root:ON_RECOGNIZING_SPEECH_FINISHED:
Mar 13 10:25:59 raspiaiy python3[13780]: {'text': 'play Brave'}
Mar 13 10:30:22 raspiaiy python3[13780]: [2018-03-13 10:30:22,027] INFO:root:ON_CONVERSATION_TURN_FINISHED:
Mar 13 10:30:22 raspiaiy python3[13780]: {'with_follow_on_turn': False}
Mar 13 10:30:22 raspiaiy python3[13780]: [2018-03-13 10:30:22,030] INFO:main:ready...
Mar 13 10:30:37 raspiaiy python3[13780]: [2018-03-13 10:30:37,688] INFO:root:ON_CONVERSATION_TURN_STARTED
Mar 13 10:30:37 raspiaiy python3[13780]: [2018-03-13 10:30:37,689] INFO:main:listening...
Mar 13 10:30:40 raspiaiy python3[13780]: [2018-03-13 10:30:40,717] INFO:root:ON_END_OF_UTTERANCE
Mar 13 10:30:40 raspiaiy python3[13780]: [2018-03-13 10:30:40,719] INFO:main:thinking...
Mar 13 10:30:40 raspiaiy python3[13780]: [2018-03-13 10:30:40,734] INFO:root:ON_RECOGNIZING_SPEECH_FINISHED:
Mar 13 10:30:40 raspiaiy python3[13780]: {'text': 'Play Sugar'}
```

Unless the arcade button is pressed, the voice-recognizer doesn't proceed past this point. the button was used to reset the recognizer after the play Brave command.

the code i have used is shown below, everything else in the action.py file is unchanged.

```
# =========================================
# Makers! Implement your own actions here.
# =========================================

class stop(object):
    """Stops VLC/YouTube"""

    def __init__(self, say, command):
        self.say = say
        self.command = command

    def run(self, voice_command):
        if self.command == "stop":
            self.say("Stopping YouTube")
            spkill = subprocess.Popen(["/usr/bin/pkill","vlc"],stdin=subprocess.PIPE)

playshell = None
class play(object):

    def __init__(self, say, keyword):
        self.say = say
        self.keyword = keyword

    def run(self, voice_command):

        spkill = subprocess.Popen(["/usr/bin/pkill","vlc"],stdin=subprocess.PIPE)
        track = voice_command.replace(self.keyword, '', 1)

        global playshell
        if (playshell == None):
            playshell = subprocess.Popen(["/usr/local/bin/mpsyt",""],stdin=subprocess.PIPE,stdout=subprocess.PIPE)

        playshell.stdin.write(bytes('/' + track + '\n1\n', 'utf-8'))
        playshell.stdin.flush()

        gpio.setmode(gpio.BCM)
        gpio.setup(23, gpio.IN)

        while gpio.input(23):
             time.sleep(1)

        pkill = subprocess.Popen(["/usr/bin/pkill","vlc"],stdin=subprocess.PIPE)





    # =========================================
    # Makers! Add your own voice commands here.
    # =========================================

    actor.add_keyword(_('play'), play(say,_('play')))

    actor.add_keyword(_('stop'), stop(say,_('stop')))

    return actor

```

if i hold the button it stops the track.

if i use the play command and then wait for the track to finish i cannot use another play command until i have pressed the button. if i try i get a response from google like, "i'm sorry i cannot do that at the moment". however, if i try ok-google what time is it, it will tell me. so it seems that the first play command is tying up the ability to play more tracks.

again, if i use the play command and wait for track to finish and then try ok-google stop, i get no response. however, if i now press the button the stop command response is played "stopping youtube". so i know the stop command is heard and registered/queued, it just doesn't run until the first play command has been terminated. further if i try a number of play voice commands in sequence i need a manual button press after each for the next to start.

**Comment by drigz** [comment] 2018-03-26 15:15
You can't process multiple custom commands at the same time. The problem is that `run()` doesn't return after it starts playing - instead, the following code waits until the button is pressed:

```
        while gpio.input(23):
             time.sleep(1)
```

You could try using a separate thread or process to wait for a button press and kill the VLC process.

We're closing this issue as this is expected behavior - `run()` needs to return before further commands can be processed. If you need more help creating custom commands, you should try asking on the [AIY Forum](https://www.raspberrypi.org/forums/viewforum.php?f=114).

**Closed as completed by drigz** 2018-03-26 15:15 UTC
