### ISSUE TITLE
Illegal instruction on running any of the demos

### ISSUE THREAD

**Issue by gomako** [google/aiyprojects-raspbian#177] opened 2017-11-15 13:46 UTC
I am using a Pi Zero W with one of the aiy kits, and whenever I try one of the demos that support the Pi Zero W (`assistant_grpc_demo.py` or `cloud_speech_demo.py`) I get `Illegal instruction` and the program exits.

There are no lights on the HAT or LED button (my button does not have a removable lamp).

The check audio program ran fine.

**Comment by t1m0thyj** [comment] 2017-11-15 13:48
The newest version of the Google Assistant SDK won't run on the Pi Zero W because it has an ARMv6 CPU. It only runs on Pis with an ARMv7 processor, like the Pi 2 and 3. You should still be able to set up "OK Google" detection on a Pi Zero using this project: https://github.com/warchildmd/google-assistant-hotword-raspi

**Comment by drigz** [comment] 2017-11-15 13:53
@gomako, are you using the AIY image or another distro?

**Comment by gomako** [comment] 2017-11-15 13:54
@t1m0thyj Ah ok, that would explain it.

@drigz I am using the AIY image, is there an AIY image that supports ARMv6?

**Comment by drigz** [comment] 2017-11-15 13:56
I would have expected the demos other than google_assistant_library.py to work, but I will try to reproduce the problem.

**Comment by gomako** [comment] 2017-11-15 13:59
It would appear that others have had this issue [reported here](https://www.raspberrypi.org/forums/viewtopic.php?f=114&t=197470&sid=677ba6dd29a70ba6c405c8cdd86012b3), and have got round it using an old image. I will try this tonight and report back.

**Comment by gomako** [comment] 2017-11-16 13:05
To update this, the old image dated 2017-05-03 lights the button and everything seems to work on the hardware side. The credentials flow goes as expected and the button press is registered, I get the speech transcript back in the terminal but the audio from the kit is always "Give me permission to help you"

**Comment by giano** [comment] 2018-02-05 16:35
D*rn! The Pi zero w has a very convenient form factor! Moving to Alexa then.

**Comment by MartinMajewski** [comment] 2018-02-28 22:29
What? Really? They should make a big disclaimer on the SDK page then! This is totally stupid... The best use case for my zeros gone! Damn you, Google! 👎

**Comment by jtgans** [comment] 2018-02-28 22:40
We are aware of this issue and are working to resolve it, please be patient with us. The root cause is due to a binary used in the assistant SDK, and we are working with teams internally to resolve this.

**Comment by PeterMalkin** [comment] 2018-03-01 19:33
You should grab the latest image from https://dl.google.com/dl/aiyprojects/aiyprojects-latest.img.xz, the assistant_grpc_demo.py and cloud_speech_demo.py should run just fine. 

The other assistant demos will not - the issue is that the processor on Pi 0 is so slow it cannot run hotword detect.

**Closed** 2018-03-01 19:33 UTC

**Comment by llealgt** [comment] 2018-07-24 04:21
I'm having this issue using a PI Zero WH using the old kit , since the new version of the kit includes a PI Zero WH i suppose there's got to be a way to run the demos using PI Zero WH, what's the difference between the new and old kit that makes this possible? and how can we use the old version kit to run all demos?

**Comment by dmitriykovalev** [comment] 2018-07-24 06:20
@llealgt Which SD-card image do you use to run demos? Have you tried the latest one from https://github.com/google/aiyprojects-raspbian/releases?

**Comment by llealgt** [comment] 2018-07-24 20:20
I think i'm using the last image, but i'll try to flash my SD-card with the latest one,after reading on the internet i got a question, does the hotword detection will work using last SD-card image version if i use a PI Zero WH , or just the other demos? And In case it does not work in Zero WH voice kit v2(which includes a Zero WH) will also only run non-hotword demos?

**Comment by ahosna** [comment] 2021-02-09 18:16
Is it possible this is still a thing ? Have zero w and google-could-texttospeech is blowing up with illegal instruction
