### ISSUE TITLE
Error 403 Request

### ISSUE THREAD

**Issue by Gravenilvec** [google/aiyprojects-raspbian#347] opened 2018-04-28 16:21 UTC
```

Hi, im trying to start my assistant librairy demo.py file but i have an error
Error 403 on trying requesting to the google assistant api .

> pi@raspberrypi:~/AIY-projects-python $ src/examples/voice/assistant_library_demo.py 
> Traceback (most recent call last):
>   File "src/examples/voice/assistant_library_demo.py", line 73, in <module>
>     main()
>   File "src/examples/voice/assistant_library_demo.py", line 67, in main
>     with Assistant(credentials) as assistant:
>   File "/opt/aiy/projects-python/src/aiy/assistant/library.py", line 33, in __init__
>     self._model_id = device_helpers.register_model_id(credentials)
>   File "/opt/aiy/projects-python/src/aiy/assistant/device_helpers.py", line 93, in register_model_id
>     r.raise_for_status()
>   File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://embeddedassistant.googleapis.com/v1alpha2/projects/gravenrpi/deviceModels/gravenrpi-voice-kit
> pi@raspberrypi:~/AIY-projects-python $ 
```

**Comment by Gravenilvec** [comment] 2018-04-29 08:01
Resolved by reinstalling the OS

**Comment by drigz** [comment] 2018-05-02 08:17
Glad you got it working!

This looks like a duplicate of #321.

**Closed as completed by drigz** 2018-05-02 08:17 UTC
