### ISSUE TITLE
Cannot erase shopping list

### ISSUE THREAD

**Issue by MarsNL** [google/aiyprojects-raspbian#180] opened 2017-11-18 19:43 UTC
Hi, I added items to the shopping list but
cannot remove them as the AIY needs to have
an connection with the Google Home app.
Is there any way to clear it?

**Comment by drigz** [comment] 2017-11-20 08:59
Not as far as I'm aware, see #6.

You could try [the support forums](https://github.com/google/aiyprojects-raspbian/blob/voicekit/README.md#support) to see if there are known workarounds.

**Comment by sheridat** [comment] 2017-11-20 10:14
Hi, go to [](https://express.google.com/  ) and sign in (if your not using chrome and aren't signed in).
On the left hand side menu you will see "list" -click on it
You can then delete whichever items you want.

**Comment by MarsNL** [comment] 2017-11-22 19:36
Thanks :))

**Comment by drigz** [comment] 2017-11-23 13:10
Good suggestion, @sheridat.

Closing as a duplicate of #6.

**Comment by dmitriykovalev** [comment] 2018-01-09 04:22
Duplicate of #6

**Closed by dmitriykovalev** 2018-01-09 04:22 UTC
