### ISSUE TITLE
VOICE KIT ISSUE

### ISSUE THREAD

**Issue by Aiyprojectsbutton** [google/aiyprojects-raspbian#667] opened 2020-02-03 16:40 UTC
We have an issue with our google voice kit led light button. Why isn't the Led Light button of the google voice kit not working or cutting on even after programming and hacking? We have replaced the voice kit once already and bought a new raspberry.

**Comment by dmitriykovalev** [comment] 2020-02-06 18:47
Duplicate of https://github.com/google/aiyprojects-raspbian/issues/670

**Closed as completed by dmitriykovalev** 2020-02-06 18:47 UTC
